project:
  type: website

website:
  site-url: https://binyu.stat.berkeley.edu
  title: "Bin Yu"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about/index.qmd
        text: About
      - href: people/index.qmd
        text: People
      - text: Papers
        href: papers/index.qmd
      - text: Books
        href: books/index.qmd
      - text: Software
        href: software/index.qmd
      - href: teaching/index.qmd
        text: Teaching
  page-footer:
    center: "&copy; 2025 Bin Yu"

format:
  html:
    theme: cosmo
    css: styles.css
    fontsize: 0.9em
    toc: true
    mainfont: "Lora"
    include-in-header:
      file: siteimprove.html
